version: "3.9"
name: dev-env-se-task-1
services:
  postgres:
    image: postgres:15.5
    container_name: postgres-task-1
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0.5
    container_name: mongo-task-1
    environment:
      MONGO_INITDB_DATABASE: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./environment/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis-task-1
    ports:
      - "6379:6379"
    command: redis-server --logLevel warning --requirepass redis
    volumes:
      - redis-data:/data

  minio:
    image: quay.io/minio/minio
    command: server /data
    container_name: minio-task-1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - minio-data:/data

volumes:
  pg-data:
  mongo-data:
  mongo-config:
  redis-data:
  minio-data: